/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package printcalculator;

import java.text.DecimalFormat;

/**
 *
 * @author al3x2450
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxPlastic = new javax.swing.JComboBox();
        jLabelMaterial = new javax.swing.JLabel();
        jLabelDiametro = new javax.swing.JLabel();
        jTextFieldDiametro = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelLongitud = new javax.swing.JLabel();
        jTextFieldLongitud = new javax.swing.JTextField();
        jLabelKg = new javax.swing.JLabel();
        jTextFieldKg = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabelTitlePlastic = new javax.swing.JLabel();
        jLabelTitleModelo = new javax.swing.JLabel();
        jComboBoxModelo = new javax.swing.JComboBox();
        jLabelModeloB = new javax.swing.JLabel();
        jLabelModeloHoras = new javax.swing.JLabel();
        jTextFieldModeloHoras = new javax.swing.JTextField();
        jLabelModeloCoste = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plastic Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jComboBoxPlastic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ABS", "PLA", "PVA", "HDPE" }));

        jLabelMaterial.setText("Material");

        jLabelDiametro.setText("Diametro (mm)");

        jLabelCantidad.setText("Cantidad");

        jLabelLongitud.setText("Longitud (mm)");

        jLabelKg.setText("Coste por kg");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelTitlePlastic.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitlePlastic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitlePlastic.setText("Coste Plastico");

        jLabelTitleModelo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitleModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleModelo.setText("Coste Modelo");

        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jComboBoxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeloActionPerformed(evt);
            }
        });

        jLabelModeloB.setText("Has hecho el modelo?");

        jLabelModeloHoras.setText("Horas dedicadas");

        jLabelModeloCoste.setText("Coste Hora (€)");

        jTextField1.setText("30");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMaterial)
                            .addComponent(jComboBoxPlastic, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDiametro)
                            .addComponent(jLabelCantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldLongitud)
                                    .addComponent(jLabelLongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelKg)
                                    .addComponent(jTextFieldKg)))
                            .addComponent(jLabelTitlePlastic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelModeloB)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelModeloHoras)
                                        .addComponent(jTextFieldModeloHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelModeloCoste)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabelTitleModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitlePlastic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitleModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaterial)
                    .addComponent(jLabelLongitud)
                    .addComponent(jLabelModeloB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPlastic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiametro)
                    .addComponent(jLabelKg)
                    .addComponent(jLabelModeloHoras)
                    .addComponent(jLabelModeloCoste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModeloHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        double density = -1;

        int material = jComboBoxPlastic.getSelectedIndex();
        String mater = new String();
        double diameter = new Double(jTextFieldDiametro.getText());
        double length = new Double(jTextFieldLongitud.getText());
        double kg = new Double(jTextFieldKg.getText());
        int cantidad = new Integer(jTextFieldCantidad.getText());

        if (material == 0) {
            density = 0.00105;  // ABS
            mater = "ABS";
        } else if (material == 1) {
            density = 0.00125;  // PLA
            mater = "PLA";
        } else if (material == 2) {
            density = 0.00119;  // PVA
            mater = "PVA";
        } else if (material == 3) {
            density = 0.00097;  // HDPE
            mater = "HDPE";
        }

        // Calculate the area of the end of the filament
        double radius = diameter / 2;
        double area = radius * radius * 3.1415926535897932384626433832795;

        // Multiply the area times the length of filament to determine the area a cylinder of material, and then multiply times the density to get the total weight of the object
        double weight = (area * length * density);
        double price = (kg / 1000) * weight;
        //Box b = new Box(5);
        //System.out.println("Diametro: " + diameter + "\nMaterial: " + mater + "\nLongitud: " + length);
        Result r = new Result();
        String resultado = "";
        DecimalFormat df = new DecimalFormat("####.##");
        if (cantidad == 1) {
            resultado = "Tipo de material: " + mater + "\n\nEstadisticas para el objeto:\n----------------------------\nPeso: " + df.format(weight) + " gramos\nCoste: " + df.format(price) + " €\nObjetos imprimibles por kilo: " + df.format(1000 / weight);
            
        } else {
            resultado = "Tipo de material: " + mater + "\nCantidad: "+cantidad+"\n\nEstadisticas para un objeto:\n----------------------------\nPeso: " + df.format(weight) + " gramos\nCoste: " + df.format(price) + " €\nObjetos imprimibles por kilo: " + df.format(1000 / weight)+"\n\nEstadisticas para " + cantidad + " objetos:\n----------------------------\nPeso total ("+cantidad+" objetos): " + df.format(weight*(double)cantidad)+" gramos\nPrecio total ("+cantidad+" objetos): "+df.format(price*(double)cantidad)+ " €";
            //Display a message box with the results for multiple items
            //System.out.println("Material type: %s\nQuantity: %d\n\nStatistics for single object:\n----------------------------\nUnit Weight: %4.4f grams\nUnit Cost: $%4.2f\nObjects printable per Kg: %4.1f\n\nStatistics for %d objects\n----------------------------\nTotal Weight(%d objects): %4.4f grams\nTotal Cost(%d objects): $%4.2f", mat, quantity, weight, price, 1000 / weight, quantity, quantity, weight * (float) quantity, quantity, price * (float) quantity);
        }
        r.setText(resultado);
        r.setVisible(true);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jComboBoxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeloActionPerformed
        // TODO add your handling code here:
        switch(jComboBoxModelo.getSelectedIndex()){
            case 0:
                jTextFieldModeloHoras.setEditable(true);
                break;
            case 1:
                jTextFieldModeloHoras.setText("1");
                jTextFieldModeloHoras.setEditable(false);
                break;
        }
    }//GEN-LAST:event_jComboBoxModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JComboBox jComboBoxModelo;
    private javax.swing.JComboBox jComboBoxPlastic;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelDiametro;
    private javax.swing.JLabel jLabelKg;
    private javax.swing.JLabel jLabelLongitud;
    private javax.swing.JLabel jLabelMaterial;
    private javax.swing.JLabel jLabelModeloB;
    private javax.swing.JLabel jLabelModeloCoste;
    private javax.swing.JLabel jLabelModeloHoras;
    private javax.swing.JLabel jLabelTitleModelo;
    private javax.swing.JLabel jLabelTitlePlastic;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldDiametro;
    private javax.swing.JTextField jTextFieldKg;
    private javax.swing.JTextField jTextFieldLongitud;
    private javax.swing.JTextField jTextFieldModeloHoras;
    // End of variables declaration//GEN-END:variables
}
